general.import = [ "~/.config/nova/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Maple Mono", style = "Regular" }
bold = { family = "Maple Mono", style = "Bold" }
italic = { family = "Maple Mono", style = "Italic" }
size = 10

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" }
]
