# Lazygit configuration
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  showIcons: true
  nerdFontsVersion: "3"
  theme:
    lightTheme: false

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

  # Pull with rebase (matches git config)
  pull:
    mode: rebase

os:
  # Open files with default editor
  editPreset: nvim
